# this code will generate same kind of error

def calculate_product(a,b)
	#do nothing
end

calculate_product(5)